# Generated by Django 5.1.5 on 2025-02-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='garment',
        ),
        migrations.AlterField(
            model_name='order',
            name='measurements',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
