# Generated by Django 5.1.5 on 2025-03-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_cartitem_fabric_cartitem_measurements_fabric_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
