# Generated by Django 5.1.5 on 2025-03-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_alter_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fabric',
        ),
        migrations.AddField(
            model_name='product',
            name='fabric',
            field=models.ManyToManyField(blank=True, to='frontend.fabric'),
        ),
    ]
